### ISSUE TITLE
SBN instruction syntax issue batch devices with hash name

### ISSUE THREAD

**Issue by Nico213** [exca/Stationeers-IC10-Automation#1]
So I am a total noob at mips and stationeers all together (got some very minor minor x86 background knowledge) so its quite possible that im wrong. But for my first personal script I was trying to use this compiler to do some stuff. 

I noticed that for my lines "ALIAS pipeHeaters = IC.Device[StructureLiquidPipeHeater].Name["pipeHeater"]" and "pipeHeaters.on = 1" it generates  "sbn -287495560 1424459751 On 1" the hashes are correct however from what I can tell is that sbn expects to load something from a register, so I think it should be e.g.: move r0 1 and then sbn .... r0.

**Comment by exca** [comment]
Hey @Nico213 .

Is your code returning an error ?

The instruction `sbn` (like all the other "set" instructions) expects a register OR a value.
So `sbn -287495560 1424459751 On 1` is correct.

**Comment by Nico213** [comment]
Hi seems you are right, at the time the code was crashing at the line count immediately after the sbn call. And this inline comment raised the suggestion for me that it only loads from a register: 
![image](https://github.com/exca/Stationeers-IC10-Automation/assets/60398347/2caa480e-53e1-4844-b649-3e5dcc7888f5)

However I just checked, set also just lists 'r?' as a possible parameter rather than something like (r?|num?) amd works fine ofc with just a val.

The thing was that introducing the move instruction before sbn initially set off all the line nummers, which i fixed in like 70-80% of the jumps, but not all, which resolved the issue and the crashing on the sbn call. Hence I thought sbn had to be from a register. This is however not the case indeed!

Thanks for the tool btw!

**Comment by exca** [comment]
OK, thanks for the details!

I'm closing the issue, if you need more support, don't hesitate to join my Discord: https://discord.gg/2rnpHTWVyV

Or to open a Discussion in Steam: https://steamcommunity.com/sharedfiles/filedetails/discussions/3108928209

I'm not always looking at my notifications on GitHub, so It can take some time if I miss it.
Thanks!

Exca.
