### ISSUE TITLE
IF-Condition -> Wrong compilation error

### ISSUE THREAD

**Issue by schlubb** [exca/Stationeers-IC10-Automation#3]
I have often noticed that IF conditions are compiled incorrectly.

Example - I try to set filtrations to idle mode when there is no pressure in the input
```basic
FT_Druck = FT_alle.PressureInput.Max
IC.Setting= FT_Druck
If FT_Druck > 0 Then
    FT_alle.Mode = 0
Else
    FT_alle.Mode = 1
endif
```

Compiler give me this Code

```basic
s db Setting r3
ble r3 0 23
sb -348054045 Mode 0
j 24
sb -348054045 Mode 1
```

That means he switches the condition instead of bge the compiler uses ble

![image](https://github.com/exca/Stationeers-IC10-Automation/assets/156251434/02d60d14-402b-47dc-9b66-dae14dfc0a79)

**Comment by exca** [comment]
Hey @schlubb ,
I'm not sure about the issue you reported.

The compiler invert the if to transform it into a jump.

So, if you want to execute `Action1` when `A > 1`, then it will jump the line when `A <=1`. By jumping the line, I mean that the `Action1` will not be executed.

In your case, `sb -348054045 Mode 0` will be executed only if `FT_Druck > 0`. So when we have `FT_Druck <= 0`, we bypass by jumping directly to the `else` instruction.

Sorry for the late reply. If you have more questions, please join our Discord, so I can get the notification quicker.
https://discord.gg/2rnpHTWVyV

Thanks,

**Comment by exca** [comment]
If I understand well your code (I understand a bit of German), when there is any pressure at the input of any filtration, you set `Mode` to 0, which disables the filters.

Maybe, you wanted to execute `Mode = 1` to enable the filter while there is any pressure at input?

**Comment by schlubb** [comment]
@exca 
No problem that you answer so "late". You've developed something great and I'm very grateful for it.

I actually made a mistake and mixed up the two filtration modes. I want to switch all filtrations to idle mode when there is no gas at the filtration input to save power.

But still if condition a > 0 set mode to what comes after the Then, if this is not true execute the condition in the Else area.

But the compiler does exactly the opposite with the brench less equal. It refers to line 23 which would be the Else condition. It should continue in line 21 and then jump to line 24.

**Comment by schlubb** [comment]
You're absolutely right, of course. I don't know why I completely misinterpreted that.
