### ISSUE TITLE
Question about custom functions

### ISSUE THREAD

**Issue by maschine34675** [exca/Stationeers-IC10-Automation#5]
I'm currently trying to use custom functions, but I'm not sure if I'm making a mistake.
As soon as I try to call a function a second time, the following error occurs:
`CRITICAL : An item with the same key has already been added. Key: customfunction`
Based on the given example code snippet:
```
main:
yield()

VAR result1 = CustomFunction(123, 234)
VAR result2 = CustomFunction(345, 456)

GOTO main

FUNCTION CustomFunction(param1, param2)
  VAR result = param1 * param2
  RETURN result
ENDFUNCTION
```
Can it even work that way?

**Comment by exca** [comment]
Hey there!

Thanks for the bug report!
I will try to correct it later today.

Your code is 100% correct, and I will use it in debug mode to check where the problem occurs.
Thanks!

**Comment by exca** [comment]
Hey @maschine34675 , please, update to the latest version. This problem is solved.
https://github.com/exca/Stationeers-IC10-Automation/tree/main/Basic-IC10

Thanks again for the bug report!

**Comment by maschine34675** [comment]
Thanks exca for the fast fix, now it's working!
