### ISSUE TITLE
Is there any way to pass an alias though?

### ISSUE THREAD

**Issue by SciFi-Bob** [exca/Stationeers-IC10-Automation#8]
Hi there, this is a great program @exca !  My hat is most definitly off to you !

I had a question that I can't seem to find in the documentation but I admit that it may be me :-)

I would like to have some constants in BASIC that survive in the MIPS code, I am thinking here of settings for the script that are 'in the clear' as it were.

For example

tconst targetO2Ratio = 0.20  

In this case the MIPS would have at the start a fixed register alias that can be used to modify the settings of the script in game without any re-complie and re-upload etc.

Thanks

**Comment by exca** [comment]
Hey there! Thanks for your feedback!

I had the same need once I used the compiler, so I implemented the "Protected Constants", check out the documentation:
https://github.com/exca/Stationeers-IC10-Automation/blob/main/Basic-IC10/Basic%20Language%20Reference.md#protected-constants-constname

For example:
```basic
const @id = 0
IC.Setting = @id
```
will be compiled in:

```mips
define id 0
s db Setting id
```
so, you just have to change the define line manually, without recompiling all the code.

I hope this helps!
